---
title: "Heterogeneous Transmission"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Heterogeneous Transmission}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Blood feeding is an interaction among humans and mosquitoes. Parasite transmission is heterogeneous because mosquito populations are spatially heterogeneous and because human behaviors are heterogeneous. Heterogeneous blood feeding and transmission is an important aspect of malaria transmission dynamics and control, and it has been implemented in `exDE` through several related concepts and constructs. 

+ **Mosquito populations** are heterogeneous over space and time. Spatial dynamics in `exDE` are organized around the concept of a *patch.* The adult mosquito populations in each *state* are assumed to be homogeneously distributed within each patch.

+ **Human population heterogeneity:** human populations are heterogeneous in several ways that affect malaria epidemiology and transmission, including age, the location of their primary residence, the type of house, mobility patterns and time spent, the use of bed nets and other personal protections, blood type, and nutrition. The design of `exDE` makes it possible to *sub-divide* the human population into an arbitrary number of homogenous strata. 

+ **Blood Feeding Search Weights:** Mosquitoes fly around to find a blood meal.  

+ **Time at Risk:** Humans spend time in different patches. 


+ environmental heterogeneity  

## Heterogeneous Biting 

**Heterogeneous Biting** is defined throughout the `exDE` implementation and documentation as a difference in the relative biting rates for two strata that are otherwise identical. The implementation relies on two concepts:

+ **blood feeding search weights** or $\left\{\omega\right\}$

+ **relative biting rates** or  $\left\{\xi\right\}$

### Blood Feeding Search Weights 

A flexible implementation is handled through the blood feeding model, which includes the the concepts of *blood feeding search weights* and *availability*. The search weights, $\left\{\omega\right\}$, are a measure of how easy it is for mosquitoes to find and blood feed on a host. The total *availability* of humans for blood feeding is:

$$W = \sum_i \omega_i H_i.$$
Since mosquitoes could feed on alternative blood hosts, we let $B = W+O,$ where $O$ is the availability of other blood hosts. Using the fully defined blood feeding model, we compute the blood feeding rates $f$ as a functional response to the total availability of blood, $B$:

$$f = F_f(B).$$
and the human fraction is:

$$q = \frac W B.$$ 

Availability is used to compute the overall blood feeding rate for mosquitoes and the human fraction (human blood meals as a fraction of all blood meals). If we assign a biting weight to a stratum, then the fraction of bites received by that stratum is: 

$$ \frac{\omega_i H_i}W.$$ 

### Relative Biting Rates 

If we let $h$ denote the *average* force of infection (FoI) for a population with multiple strata, and $\xi_i$ the frailty term, then the FoI for the $i^{th}$ stratum is $$h_i = \xi_i h;$$ 

We let $H_i$ denote the size of the $i^{th}$ population, where $$H = \sum_i H_i.$$ 

The relative biting rates are constrained such that 
$$\sum_i \xi_i \frac{H_i}H = 1$$ 
For example, if 20% of the population gets bitten at a rate that is twice as high as the population  average, then the other 80% must get bitten (on average) at a rate that is 3/4 the population average, since:

$$ 2\;(0.2)+ 0.75\;(0.8)= 1$$ 



Relative biting rates are computed automatically from the blood feeding search weights, $\left\{\omega\right\},$ where 

$$\xi_i = \omega_i \frac H W.$$

## Heterogeneous Mixing


