
#' Plot adult mosquito population density
#'
#' @param pars a list that defines an `exDE` model (*e.g.*,  generated by `xde_setup()`)
#' @param clrs a vector of colors
#' @param llty an integer (or integers) to set the `lty` for plotting
#' @param stable a logical: set to FALSE for `orbits` and TRUE for `stable_orbits`
#' @param add_axes a logical: plot axes only if TRUE
#'
#' @export
xde_plot_M = function(pars, clrs="darkblue", llty=1, stable=FALSE, add_axes=TRUE){
  vars=with(pars$outputs,if(stable==TRUE){stable_orbits}else{orbits})

  if(add_axes == TRUE) with(vars$MYZ,
                            plot(time, 0*time, type = "n", ylim = range(0,max(M)),
                                 ylab = "Mosquito Density", xlab = "Time"))

  xde_lines_M(vars$MYZ, pars, clrs, llty)
}

#' Add lines for adult mosquito population density
#'
#' @param MYZ a list the output of `exDE::parse_deout()`
#' @param pars a list that defines an `exDE` model (*e.g.*,  generated by `xde_setup()`)
#' @param clrs a vector of colors
#' @param llty an integer (or integers) to set the `lty` for plotting
#'
#' @export
xde_lines_M = function(MYZ, pars, clrs="darkblue", llty=1){
  with(MYZ,{
   if(pars$nPatches==1) lines(time, M, col=clrs[1], lty = llty[1])
   if(pars$nPatches>1){
      if (length(clrs)==1) clrs=rep(clrs, pars$nPatches)
      if (length(llty)==1) llty=rep(llty, pars$nPatches)
      for(i in 1:pars$nPatches){
        lines(time, M[,i], col=clrs[i], lty = llty[i])
      }
    }
})}

#' Plot the density of infected and infective mosquitoes
#'
#' @param pars a list that defines an `exDE` model (*e.g.*,  generated by `xde_setup()`)
#' @param Yclrs a vector of colors for infected mosquitoes
#' @param Zclrs a vector of colors for infective mosquitoes
#' @param llty an integer (or integers) to set the `lty` for plotting
#' @param stable set to FALSE for `orbits` and TRUE for `stable_orbits`
#' @param add_axes to plot axes only if TRUE
#'
#' @export
xde_plot_YZ = function(pars, Yclrs = "purple", Zclrs="darkred", llty=1, stable=FALSE, add_axes=TRUE){
  vars=with(pars$outputs,if(stable==TRUE){stable_orbits}else{orbits})

  if(add_axes == TRUE)
    with(vars$MYZ,
         plot(time, 0*time, type = "n", ylim = range(0,max(Y)),
              ylab = "Mosquito Density", xlab = "Time"))

  xde_lines_YZ(vars$MYZ, pars, Yclrs, Zclrs, llty)
}

#' Add lines for the density of infected and infective mosquitoes
#'
#' @param MYZ a list the output of `exDE::parse_deout()`
#' @param pars a list that defines an `exDE` model (*e.g.*,  generated by `xde_setup()`)
#' @param Yclrs a vector of colors
#' @param Zclrs a vector of colors
#' @param llty an integer (or integers) to set the `lty` for plotting
#'
#' @export
xde_lines_YZ = function(MYZ, pars, Yclrs="purple", Zclrs = "darkred", llty=1){
  with(MYZ,{
    if(pars$nPatches==1){
      lines(time, Y, col=Yclrs[1], lty = llty[1])
      lines(time, Z, col=Zclrs[1], lty = llty[1])
    }
    if(pars$nPatches>1){
      if (length(Yclrs)==1) Yclrs=rep(Yclrs, pars$nPatches)
      if (length(Zclrs)==1) Zclrs=rep(Zclrs, pars$nPatches)
      if (length(llty)==1) llty=rep(llty, pars$nPatches)

      for(i in 1:pars$nPatches){
        lines(time, Y[,i], col=Yclrs[i], lty = llty[i])
        lines(time, Z[,i], col=Zclrs[i], lty = llty[i])
      }
    }
})}

#' Plot the fraction of infected and infective mosquitoes
#'
#' @param pars a list that defines an `exDE` model (*e.g.*,  generated by `xde_setup()`)
#' @param Yclrs a vector of colors for infected mosquitoes
#' @param Zclrs a vector of colors for infective mosquitoes
#' @param llty an integer (or integers) to set the `lty` for plotting
#' @param stable a logical, set to FALSE for `orbits` and TRUE for `stable_orbits`
#' @param add_axes a logical to plot axes only if TRUE
#'
#' @export
xde_plot_YZ_fracs = function(pars, Yclrs = "purple", Zclrs = "darkred", llty=1, stable=FALSE, add_axes=TRUE){
  vars=with(pars$outputs,if(stable==TRUE){stable_orbits}else{orbits})

  if(add_axes == TRUE)
    with(vars$MYZ,
         plot(time, 0*time, type = "n", ylim = range(0,1),
              ylab = "Fraction Infected", xlab = "Time"))

  xde_lines_YZ_fracs(vars$MYZ, pars, Yclrs, Zclrs, llty)
}

#' Add lines for the fraction of infected and infective mosquitoes
#'
#' @param MYZ a list the output of `exDE::parse_deout()`
#' @param pars a list that defines an `exDE` model (*e.g.*,  generated by `xde_setup()`)
#' @param Yclrs a vector of colors for infected mosquitoes
#' @param Zclrs a vector of colors for infective mosquitoes
#' @param llty an integer (or integers) to set the `lty` for plotting
#'
#' @export
xde_lines_YZ_fracs = function(MYZ, pars, Yclrs="purple", Zclrs="darkred", llty=1){
  with(MYZ,{
    if(pars$nPatches==1) {
      lines(time, y, col=Yclrs, lty = llty[1])
      lines(time, z, col=Zclrs, lty = llty[1])
    }
    if(pars$nPatches>1){
      if (length(Yclrs)==1) Yclrs=rep(Yclrs, pars$nPatches)
      if (length(Zclrs)==1) Zclrs=rep(Zclrs, pars$nPatches)
      if (length(llty)==1) llty=rep(llty, pars$nPatches)

      for(i in 1:pars$nPatches){
        lines(time, y[,i], col=Yclrs[i], lty = llty[i])
        lines(time, z[,i], col=Zclrs[i], lty = llty[i])
      }
    }
})}
