#' Plot the EIR *vs.* time
#'
#' @param pars a [list] that defines an `exDE` model (*e.g.*,  generated by `exDE::xde_setup()`)
#' @param clrs a [character] vector of colors
#' @param llty an [integer] (or integers) to set the `lty` for plotting
#' @param stable a [logical] set to FALSE for `orbits` and TRUE for `stable_orbits`
#' @param add_axes a [logical] to plot axes only if TRUE
#'
#' @export
xde_plot_EIR <- function(pars, clrs="black", llty=1, stable=FALSE, add_axes=TRUE){
  vars=with(pars$outputs,if(stable==TRUE){stable_orbits}else{orbits})

  if(add_axes==TRUE)
    with(vars$terms,{
      plot(time, eir, type = "n", xlab = "Time", ylab = "dEIR", ylim = range(0, eir))
    })

  xde_lines_EIR(vars$terms, pars, clrs, llty)
}

#' Add lines for the EIR *vs.* time
#'
#' @param terms a [list] with the outputs of `exDE::parse_deout()`
#' @param pars a [list] that defines an `exDE` model (*e.g.*,  generated by `exDE::xde_setup()`)
#' @param clrs a [character] vector of colors
#' @param llty an [integer] (or integers) to set the `lty` for plotting
#'
#' @export
xde_lines_EIR <- function(terms, pars, clrs="black", llty=1){
  with(terms,{
    if(pars$nStrata==1)
      lines(time, eir, col=clrs, lty = llty)
    if(pars$nStrata>1){
      if(length(clrs)==1) clrs=rep(clrs, pars$nStrata)
      if(length(llty)==1) llty=rep(llty, pars$nStrata)
      for(i in 1:pars$nStrata)
        lines(time, eir[,i], col=clrs[i], lty = llty)
    }
  })
}

#' Plot the annualized EIR *vs.* time
#'
#' @param pars a [list] that defines an `exDE` model (*e.g.*,  generated by `exDE::xde_setup()`)
#' @param clrs a [character] vector of colors
#' @param llty an [integer] (or integers) to set the `lty` for plotting
#' @param stable a [logical] set to FALSE for `orbits` and TRUE for `stable_orbits`
#' @param add_axes a [logical] to plot axes only if TRUE
#'
#' @export
xde_plot_aEIR <- function(pars, clrs="black", llty=1, stable=FALSE, add_axes=TRUE){
  vars=with(pars$outputs,if(stable==TRUE){stable_orbits}else{orbits})

  if(add_axes==TRUE)
    with(vars$terms,{
      aeir = 365*eir
      plot(time, aeir, type = "n", xlab = "Time", ylab = "aEIR", ylim = range(0, aeir))
    })
  xde_lines_aEIR(vars$terms, pars, clrs, llty)
}

#' Add lines for the annualized EIR *vs.* time
#'
#' @param terms a [list] with the outputs of `parse_deout()`
#' @param pars a [list] that defines an `exDE` model (*e.g.*,  generated by `exDE::xde_setup()`)
#' @param clrs a [character] vector of colors
#' @param llty an [integer] (or integers) to set the `lty` for plotting
#'
#' @export
xde_lines_aEIR <- function(terms, pars, clrs="black", llty=1){
  with(terms,{
    aeir = 365*eir
    if(pars$nStrata==1) lines(time, aeir, col=clrs)
    if(pars$nStrata>1){
      if (length(clrs)==1) clrs=rep(clrs, pars$nStrata)
      for(i in 1:pars$nStrata)
        lines(time, aeir[,i], col=clrs[i])
    }
  })
}

#' Plot the prevalence / parasite rate (PR) from a model of human infection and immunity
#'
#' @param pars a [list] that defines an `exDE` model (*e.g.*,  generated by `xde_setup()`)
#' @param stable a [logical] set to FALSE for `orbits` and TRUE for `stable_orbits`
#' @param add_axes a [logical] to plot axes only if TRUE
#' @param clrs a [character] vector of colors
#' @param llty an [integer] (or integers) that specifies `lty` for plotting
#'
#' @export
xde_plot_PR = function(pars, clrs="black", llty=1, stable=FALSE, add_axes=TRUE){
  vars=with(pars$outputs,if(stable==TRUE){stable_orbits}else{orbits})

  if(add_axes==TRUE)
    with(vars$terms,
         plot(time, 0*time + 1, type = "n", ylim = c(0,1),
              ylab = "# Infected", xlab = "Time"))

  xde_lines_PR(vars$terms, pars, clrs, llty)
}

#' Add lines for the prevalence / parasite rate (PR) from a model of human infection and immunity
#'
#' @param terms a [list] with the outputs of `exDE::parse_deout()`
#' @param pars a [list] that defines an `exDE` model (*e.g.*,  generated by `xde_setup()`)
#' @param clrs a [character] vector of colors
#' @param llty an [integer] (or integers) that specifies `lty` for plotting
#'
#' @export
xde_lines_PR = function(terms, pars, clrs="black", llty=1){
  with(terms,{
    if(pars$nStrata==1) lines(time, pr, col=clrs)
    if(pars$nStrata>1){
      if (length(clrs)==1) clrs=rep(clrs, pars$nStrata)
      for(i in 1:pars$nStrata)
        lines(time, pr[,i], col=clrs[i])
    }
  })
}


