#' Plot the EIR *vs.* time
#'
#' @param pars a list that defines an `exDE` model (*e.g.*,  generated by `exDE::xde_setup()`)
#' @param i the host species index
#' @param clrs a vector of colors
#' @param llty an integer (or integers) to set the `lty` for plotting
#' @param stable a logical: set to FALSE for `orbits` and TRUE for `stable_orbits`
#' @param add_axes a logical: plot axes only if TRUE
#'
#' @export
xde_plot_EIR <- function(pars, i=1, clrs="black", llty=1, stable=FALSE, add_axes=TRUE){
  vars=with(pars$outputs,if(stable==TRUE){stable_orbits}else{orbits})

  if(add_axes==TRUE)
    with(vars$terms,{
      plot(time, eir, type = "n", xlab = "Time", ylab = "dEIR", ylim = range(0, eir))
    })

  xde_lines_EIR(time, vars$terms$eir[[i]], pars$Hpar[[i]]$nStrata, clrs, llty)
}

#' Add lines for the EIR *vs.* time
#'
#' @param time the time
#' @param EIR the entomological inoculation rate
#' @param nStrata the number of human / host population strata
#' @param clrs a vector of colors
#' @param llty an integer (or integers) to set the `lty` for plotting
#'
#' @export
xde_lines_EIR <- function(time, EIR, nStrata, clrs="black", llty=1){

  if(nStrata==1)
    lines(time, EIR, col=clrs, lty = llty)
  if(nStrata>1){
    if(length(clrs)==1) clrs=rep(clrs, nStrata)
    if(length(llty)==1) llty=rep(llty, nStrata)
    for(i in 1:nStrata)
      lines(time, EIR[,i], col=clrs[i], lty = llty)
  }
}

#' Plot the annualized EIR *vs.* time
#'
#' @param pars a list that defines an `exDE` model (*e.g.*,  generated by `exDE::xde_setup()`)
#' @param clrs a vector of colors
#' @param llty an integer (or integers) to set the `lty` for plotting
#' @param stable a logical: set to FALSE for `orbits` and TRUE for `stable_orbits`
#' @param add_axes a logical: plot axes only if TRUE
#'
#' @export
xde_plot_aEIR <- function(pars, i=1, clrs="black", llty=1, stable=FALSE, add_axes=TRUE){
  vars=with(pars$outputs,if(stable==TRUE){stable_orbits}else{orbits})

  if(add_axes==TRUE)
    with(vars$terms,{
      aeir = 365*eir
      plot(time, aeir, type = "n", xlab = "Time", ylab = "aEIR", ylim = range(0, aeir))
    })
  xde_lines_aEIR(time, vars$terms$eir[[i]], pars$Hpar[[i]]$nStrata, clrs, llty)
}

#' Add lines for the annualized EIR *vs.* time
#'
#' @param time the time
#' @param EIR the entomological inoculation rate
#' @param nStrata the number of human / host population strata
#' @param clrs a vector of colors
#' @param llty an integer (or integers) to set the `lty` for plotting
#'
#' @export
xde_lines_aEIR <- function(time, EIR, nStrata,  clrs="black", llty=1){
 aeir = 365*EIR
 if(pars$nStrata==1) lines(time, aeir, col=clrs)
 if(pars$nStrata>1){
   if (length(clrs)==1) clrs=rep(clrs, pars$nStrata)
   for(i in 1:pars$nStrata)
     lines(time, aeir[,i], col=clrs[i])
 }

}

#' Plot the prevalence / parasite rate (PR) from a model of human infection and immunity
#'
#' @param pars a list that defines an `exDE` model (*e.g.*,  generated by `xde_setup()`)
#' @param i the host species index
#' @param clrs a vector of colors
#' @param llty an integer (or integers) that specifies `lty` for plotting
#' @param stable a logical: set to FALSE for `orbits` and TRUE for `stable_orbits`
#' @param add_axes a logical: plot axes only if TRUE
#'
#' @export
xde_plot_PR = function(pars, i=1, clrs="black", llty=1, stable=FALSE, add_axes=TRUE){
  vars=with(pars$outputs,if(stable==TRUE){stable_orbits}else{orbits})

  if(add_axes==TRUE)
    with(vars$terms,
         plot(time, 0*time + 1, type = "n", ylim = c(0,1),
              ylab = "Prevalence", xlab = "Time"))

  xde_lines_PR(time, vars$terms$PR[[i]], pars$Hpar[[i]]$nStrata, clrs, llty)
}

#' Add lines for the prevalence / parasite rate (PR) from a model of human infection and immunity
#'
#' @param time the time
#' @param PR the computed parasite rate
#' @param nStrata the number of human / host population strata
#' @param clrs a vector of colors
#' @param llty an integer (or integers) that specifies `lty` for plotting
#'
#' @export
xde_lines_PR = function(time, PR, nStrata, clrs="black", llty=1){

  if(nStrata==1) lines(time, PR, col=clrs[1], lty = llty[1])
  if(nStrata>1){
    if (length(clrs)==1) clrs=rep(clrs, nStrata)
    if (length(llty)==1) llty=rep(llty, nStrata)
    for(i in 1:nStrata)
      lines(time, PR[,i], col=clrs[i], lty = llty[i])
  }

}


